---
- hosts: server-staging
  become: true
  tasks:
    - name: Copy WAR to webapps
      copy: src=target/greetings-0.1-SNAPSHOT.war dest=/opt/tomcat/webapps/hello.war owner=tomcat group=tomcat mode=0744

    